# Generated by Django 4.2.7 on 2026-08-11 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_bookings', '0004_alter_booking_user_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(default='f34c74a9-18c7-4d2b-8730-ba555bb35d81', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticket_bookings.event'),
            preserve_default=False,
        ),
    ]
