# Generated by Django 4.2.7 on 2026-08-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_bookings', '0005_ticket_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
