# Generated by Django 4.2.7 on 2026-08-31 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_bookings', '0007_alter_booking_status_alter_event_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='combine_tickets',
            field=models.BooleanField(default=False, help_text='Combine all tickets into a single file'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_format',
            field=models.CharField(choices=[('pdf', 'PDF - Print Ready'), ('png', 'PNG - Image Format'), ('both', 'Both PDF and PNG')], default='pdf', help_text='Select the format for ticket delivery', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='tickets_per_page',
            field=models.IntegerField(default=4, help_text='Number of tickets per page (for combined tickets)'),
        ),
    ]
