# Generated by Django 4.2.7 on 2026-08-31 09:23


from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_bookings', '0008_event_combine_tickets_event_ticket_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTemplateType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='📄', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_templates/')),
                ('config', models.JSONField(default=dict, help_text='\n        JSON configuration for dynamic content placement on the template.\n        Example:\n        {\n            "fields": {\n                "event_title": {"x": 0.5, "y": 0.22, "font_size": 32, "color": "#D69E2E", "align": "center"},\n                "event_date": {"x": 0.5, "y": 0.34, "font_size": 36, "color": "#1A202C", "align": "center"},\n                "venue": {"x": 0.5, "y": 0.88, "font_size": 14, "color": "#4A5568", "align": "center"},\n                "qr_code": {"x": 0.18, "y": 0.58, "size": 140}\n            },\n            "template_type": "ticket",\n            "page_size": "A4",\n            "orientation": "landscape"\n        }\n    ')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='ticket_bookings.event')),
                ('template_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='ticket_bookings.eventtemplatetype')),
            ],
            options={
                'ordering': ['template_type', 'created_at'],
                'unique_together': {('event', 'template_type', 'name')},
            },
        ),
    ]
