# Generated by Django 4.2.7 on 2026-09-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_bookings', '0009_eventtemplatetype_eventtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('sold_out', 'Sold Out'), ('postponed', 'Postponed')], default='draft', max_length=20),
        ),
    ]
