# Generated by Django 4.2.7 on 2026-09-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_bookings', '0010_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_organizer',
            field=models.BooleanField(default=False),
        ),
    ]
