# Generated by Django 4.2.7 on 2026-09-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_bookings', '0011_userprofile_is_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtemplate',
            name='config',
            field=models.JSONField(default=dict, help_text='\n        JSON configuration for dynamic content placement on the template.\n        Example:\n        {\n            "fields": {\n                "event_title": {"x": 0.5, "y": 0.22, "font_size": 32, "color": "#D69E2E", "align": "center"},\n                "event_date": {"x": 0.5, "y": 0.34, "font_size": 36, "color": "#1A202C", "align": "center"},\n                "venue": {"x": 0.5, "y": 0.88, "font_size": 14, "color": "#4A5568", "align": "center"},\n                "qr_code": {"x": 0.18, "y": 0.58, "size": 140}\n            },\n            "template_type": "ticket",\n            "page_size": "A4",\n            "orientation": "landscape"\n        }\n        '),
        ),
    ]
