# Generated by Django 4.2.7 on 2026-09-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_bookings', '0012_alter_eventtemplate_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinlog',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
