# Generated by Django 4.2.7 on 2026-09-26 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket_bookings', '0016_cancellation_policies_and_discount_enhancements'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='discountusage',
            new_name='disc_usage_disc_user_idx',
            old_name='discount_usage_disc_user_idx',
        ),
        migrations.AddField(
            model_name='event',
            name='cancellation_policy_text',
            field=models.TextField(blank=True, help_text='Free-text cancellation terms. Shown to the customer when no structured policy (FK) is attached, or as an additional note.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cancellation_policy_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Frozen copy of the event policy rules at booking time. Do not mutate — used for refund calculation on cancellation.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cancellationpolicy',
            name='is_default',
            field=models.BooleanField(default=False, help_text='If true, this policy is preselected when creating a new event for this organizer. Only one policy per organizer may be default.'),
        ),
        migrations.AlterField(
            model_name='cancellationpolicy',
            name='organizer',
            field=models.ForeignKey(help_text='Policy owner. Only the owner (or admin) can edit.', on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cancellationpolicy',
            name='rules',
            field=models.JSONField(default=dict, help_text='Policy rules. See services/cancellation_policy.py for schema. Must include "version" and "refund_tiers".'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='applicable_events',
            field=models.ManyToManyField(blank=True, help_text='If empty, discount applies to all events by this organizer.', related_name='applicable_discounts', to='ticket_bookings.event'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='first_time_buyers_only',
            field=models.BooleanField(default=False, help_text='If true, only users with no prior paid bookings can use this.'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='max_uses_per_user',
            field=models.IntegerField(blank=True, help_text='Max times a single customer can use this code. Null = unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='min_ticket_count',
            field=models.IntegerField(default=0, help_text='Minimum number of tickets in the booking to apply. 0 = no minimum.'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='stackable',
            field=models.BooleanField(default=False, help_text='Whether this discount can be combined with others on one booking.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cancellation_policy',
            field=models.ForeignKey(blank=True, help_text='Reusable cancellation policy. If null, no structured refunds are offered — the free-text field may still be shown.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='ticket_bookings.cancellationpolicy'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cancellation_fee_applied',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat cancellation fee deducted from the refund.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cancelled_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='net_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price actually paid for this ticket after any booking-level discount proration. This is the base for refund calculation.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Refund amount for this ticket due to cancellation. This is separate from the booking-level refund_amount.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='refund_percent_applied',
            field=models.IntegerField(default=0, help_text='Refund percentage from the policy tier that applied.'),
        ),
        migrations.AddIndex(
            model_name='discountusage',
            index=models.Index(fields=['booking'], name='disc_usage_booking_idx'),
        ),
    ]
