# Generated by Django 4.2.7 on 2026-09-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_bookings', '0018_drop_legacy_event_cancellation_policy_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtemplate',
            name='config',
            field=models.JSONField(default=dict, help_text='Layout configuration. See the docstring on this model for the schema. Coordinates are fractions of canvas width/height (0.0–1.0), or absolute pixels if >1. Unknown field names are ignored; missing fields fall back to defaults in ticket_generator.DEFAULT_FIELD_CONFIG.'),
        ),
    ]
