name: Build Android APK on Production Release

on:
  push:
    branches:
      - Production_Release

jobs:
  build_android:
    name: Build Android APK
    type: build
    params:
      platform: android
      profile: preview